packages:
  - packages/*
  - "!**/test/**"
catalog:
  globals: "^15.15.0"
  eslint: ^9.21.0
  eslint-plugin-react: "^7.37.4"
  eslint-plugin-react-hooks: "^5.1.0"
  eslint-plugin-react-refresh: "^0.4.19"
  prettier: ^3.5.2
  react: "^19.0.0"
  react-dom: "^19.0.0"
  typescript: ^5.7.3
  typescript-eslint: ^8.25.0
  uuid: "^11.1.0"
  vitest: ^3.0.7
  vite: ^6.2.0
  zustand: "^5.0.3"
  "@eslint/js": ^9.21.0
  "@vitejs/plugin-react": ^4.3.4
  "@tari-project/tarijs": ^0.4.0
  "@tari-project/typescript-bindings": ^1.5.1
  "@tari-project/wallet-connect-provider": ^0.4.0
  "@tari-project/wallet-daemon-provider": ^0.4.0
  "@types/node": ^22.13.5
  "@types/react": "^19.0.10"
  "@types/react-dom": "^19.0.4"
  "@types/vscode": ^1.97.0
  "@types/vscode-webview": ^1.57.5
